// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrjyxkpygmidaxvzqqnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyanl4a3B5Z21pZGF4dnpxcW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDIzODcsImV4cCI6MjA2Mzg3ODM4N30.eftkf4EK3IQ3JR8Aa2a0CGEHD6mPbDCWVciyzg47IKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);